import test from 'node:test';
import assert from 'node:assert/strict';
import { nextFollowupDate, scoreProspect, classifyReplyFallback, canAutoReply, normalizeEmail, isValidEmail, quoteMetrics, safePercentage, mapBrevoEvent, supportRoute, prioritizeProductIdeas } from '../server/logic.js';
import { buildCeoMetrics, weeklyRecommendations } from '../server/ceo.js';

test('follow-up schedule uses J+2 J+5 J+10',()=>{assert.match(nextFollowupDate('2026-10-01',0),/^2026-10-03/);assert.match(nextFollowupDate('2026-10-01',1),/^2026-10-06/);assert.match(nextFollowupDate('2026-10-01',2),/^2026-10-11/);assert.equal(nextFollowupDate('2026-10-01',3),null)});
test('ideal 1-10 person service business scores highly',()=>{const r=scoreProspect({employee_count:6,estimated_quotes_per_month:18,uses_digital_tools:true,is_service_business:true,website:'https://x.fr',email:'contact@x.fr',role:'Gérant'});assert.ok(r.score>=90)});
test('low-signal prospect is not falsely qualified',()=>{assert.ok(scoreProspect({employee_count:100,estimated_quotes_per_month:0,is_service_business:false,email:'person@gmail.com'}).score<55)});
test('reply classifier covers opt-out, timing, pricing and interest',()=>{assert.equal(classifyReplyFallback('STOP merci').category,'opt_out');assert.equal(classifyReplyFallback('Recontactez-moi dans trois mois').category,'not_now');assert.equal(classifyReplyFallback('Quel est le prix ?').category,'pricing');assert.equal(classifyReplyFallback('Je veux une démo').category,'interested');assert.equal(canAutoReply(classifyReplyFallback('STOP')),true)});
test('email normalization validates syntax without pretending domain type',()=>{assert.equal(normalizeEmail(' TEST@EXAMPLE.COM '),'test@example.com');assert.equal(isValidEmail('test@example.com'),true);assert.equal(isValidEmail('bad'),false);assert.equal(isValidEmail('person@gmail.com'),true)});
test('win rate only uses decided quotes',()=>{const m=quoteMetrics([{status:'won',amount:100},{status:'lost',amount:200},{status:'open',amount:300,next_followup_at:'2999-01-01T00:00:00Z'}]);assert.equal(m.winRate,50);assert.equal(m.openAmount,300);assert.equal(m.wonAmount,100)});
test('safe percentages and CEO funnel metrics',()=>{assert.equal(safePercentage(1,4),25);const m=buildCeoMetrics({visitors:100,signups:20,activated:10,paying:2,outreachSent:50,replies:5,meetings:1});assert.equal(m.signupRate,20);assert.equal(m.activationRate,50);assert.equal(m.paidConversion,20);assert.equal(m.replyRate,10)});
test('Brevo events map to internal events',()=>{assert.equal(mapBrevoEvent('hard_bounce'),'bounced');assert.equal(mapBrevoEvent('uniqueOpened'),'opened');assert.equal(mapBrevoEvent('unsubscribed'),'opt_out');assert.equal(mapBrevoEvent('unknown'),null)});
test('support escalates sensitive topics',()=>{assert.equal(supportRoute('Je veux supprimer mes données').needs_human,true);assert.equal(supportRoute('Ma carte a été débitée').topic,'billing');assert.equal(supportRoute('Comment marche J+5 ?').needs_human,false)});
test('product ideas require repeated evidence before CEO recommendation',()=>{const insights=[{requested_feature:'Gmail',confidence:.9},{requested_feature:'gmail',confidence:.8},{requested_feature:'Gmail',confidence:.7},{requested_feature:'SMS',confidence:.9}];const p=prioritizeProductIdeas(insights);assert.equal(p[0].feature,'gmail');assert.equal(p[0].requests,3);const m=buildCeoMetrics({signups:10,activated:3});assert.ok(weeklyRecommendations(m,insights).some(x=>x.includes('Gmail')||x.includes('gmail')))});
