FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --no-audit --no-fund
COPY . .
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPPORT_EMAIL
ARG VITE_CONTACT_EMAIL
ARG VITE_BILLING_ENABLED
ARG APP_URL
ARG VITE_LEGAL_ENTITY_TYPE
ARG VITE_LEGAL_NAME
ARG VITE_LEGAL_FORM
ARG VITE_LEGAL_CAPITAL
ARG VITE_LEGAL_ADDRESS
ARG VITE_LEGAL_EMAIL
ARG VITE_LEGAL_REGISTRATION
ARG VITE_LEGAL_VAT
ARG VITE_LEGAL_PHONE
ARG VITE_PUBLICATION_DIRECTOR
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPPORT_EMAIL=$VITE_SUPPORT_EMAIL
ENV VITE_CONTACT_EMAIL=$VITE_CONTACT_EMAIL
ENV VITE_BILLING_ENABLED=$VITE_BILLING_ENABLED
ENV APP_URL=$APP_URL
ENV VITE_LEGAL_ENTITY_TYPE=$VITE_LEGAL_ENTITY_TYPE
ENV VITE_LEGAL_NAME=$VITE_LEGAL_NAME
ENV VITE_LEGAL_FORM=$VITE_LEGAL_FORM
ENV VITE_LEGAL_CAPITAL=$VITE_LEGAL_CAPITAL
ENV VITE_LEGAL_ADDRESS=$VITE_LEGAL_ADDRESS
ENV VITE_LEGAL_EMAIL=$VITE_LEGAL_EMAIL
ENV VITE_LEGAL_REGISTRATION=$VITE_LEGAL_REGISTRATION
ENV VITE_LEGAL_VAT=$VITE_LEGAL_VAT
ENV VITE_LEGAL_PHONE=$VITE_LEGAL_PHONE
ENV VITE_PUBLICATION_DIRECTOR=$VITE_PUBLICATION_DIRECTOR
RUN npm run check && npm run build

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm install --omit=dev --no-audit --no-fund
COPY --from=build /app/dist ./dist
COPY --from=build /app/server ./server
EXPOSE 3000
CMD ["node","server/index.js"]
